
language: python
python:
  - "3.6-dev"
install:
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage
services:
  - postgresql
addons:
  - postgresql: "9.6"
  - apt:
      - packages:
        - postgresql-10
        - postgresql-client-10
postgres:
  - adapter: postgresql
env:
  - DB=postgres
  - global:
    - PGPORT=5433
notifications:
  - false
before_script:
  - psql -c 'create database test_hello_books_db;' -U postgres
after_success: "coveralls"