
language: python
python:
  - "3.6-dev"
install:
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage
services:
  - postgresql
notifications:
  - false
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
after_success: "coveralls"