
language: python
python:
  - "3.6-dev"
install:
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage
services:
  - postgresql
postgres:
  - adpter: postgresql
env:
  - DB=postgress
notifications:
  - false
before_script:
  - psql -c 'create database test_hello_books_db;' -U postgres
after_success: "coveralls"