"""empty message

Revision ID: 59af60e6c967
Revises: 244c92608595
Create Date: 2018-05-08 16:05:12.796718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59af60e6c967'
down_revision = '244c92608595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrowed_books', 'is_returned')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_books', sa.Column('is_returned', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
