"""empty message

Revision ID: fda89a4f7974
Revises: a40308505dd6
Create Date: 2018-05-05 23:50:44.991949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda89a4f7974'
down_revision = 'a40308505dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowed_book_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_borrowed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrowed_book_list')
    # ### end Alembic commands ###
